<!-- start banner Area -->
<section class="banner-area relative" id="home">
   <div class="overlay overlay-bg"></div>
   <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
         <div class="about-content col-lg-12">
            <h1 class="text-white">
               Term & Condition
            </h1>
            <p class="text-white link-nav"><a href="<?php echo base_url(); ?>">Home </a>  <span class="lnr lnr-arrow-right"></span>
               <a href="<?php echo base_url(); ?>term-condition">Term & Condition</a>
            </p>
         </div>
      </div>
   </div>
</section>
<!-- End banner Area -->
<section class="service-area pb-4" id="term-condition">
   <div class="container">
   	  <h1 class="text-center py-5">Term & Condition</h1>
      <div class="row m-auto">

			1. Introduction. Please read this page carefully. It contains the terms and conditions (the "Terms and Conditions") governing your access to and use of the CareerBuilder Web Sites and the Services (as each are defined below) provided by CareerBuilder, LLC or one of its divisions (collectively, "CareerBuilder"). If you do not accept these Terms and Conditions or you do not meet or comply with their provisions, you may not use the CareerBuilder Web Sites or Services. These Terms and Conditions are effective as of May 7, 2019.

			2. Binding Agreement. These Terms and Conditions (as they may be amended from time to time by CareerBuilder), together with your Advertising and Candidate Search Service Agreement (if applicable), form a binding agreement (the "Agreement") between you and CareerBuilder. Your access to or use of the CareerBuilder Web Sites or Services indicates your acceptance of these Terms and Conditions. You are agreeing to use the Sites at your own risk.

			3. Certain Definitions. The following definitions apply to this Agreement:

			3.1 "CareerBuilder Materials" includes any materials, methodologies, implementation plans or other intellectual property used during the provision of Services.

			3.2 "CareerBuilder Web Site" or the "Site" (collectively, the "CareerBuilder Websites" or the "Sites") means any web site under CareerBuilder's control, whether partial or otherwise and includes such Site's Content, CareerBuilder Materials and Services (as applicable in each context).

			3.3 "Content" means CareerBuilder's web pages, web forms, programming (including software code used on the Sites and in the Services, including (i) tools, kits, and object libraries, (ii) all third-party or open source code embedded therein, and (iii) any upgrades, updates, releases, fixes, enhancements or modifications to the foregoing), graphics, images, design (color combinations and page layout), text, information, data, resumes stored in various commercial databases operated and licensed by CareerBuilder (including, among others, its "Resume Database," "Salary Calculator Database," "TalentStream Supply & Demand Database" and the Recruitment Edge Database), data submitted via the Sites by Users and other content made available through the Sites by CareerBuilder.

			3.5 "Document" refers to any posting to a Site, whether job or resume.

			3.6 "Employer" means a person or entity that is accessing a Site to post a job or utilizing the Services for any reason related to the purpose of seeking candidates for employment.

			3.7 "Employer Materials" includes any brochures, emails, sample job postings, web site content, career fair material, audio, videos, photographs, logos, trademarks, service marks, domain names, documents or other materials provided by Employer, if any, for use in connection with the Services.

			3.9 "Job Seeker" means a User who is accessing a Site to search for a job or in any other capacity except as an Employer.

			3.10 "Services" means any services provided by CareerBuilder or its agents described herein and specified more fully in the Service Activation Agreement.

			3.12 "User" refers to any individual or entity that uses any aspect of the Sites.

			3.13 "You" or "you" means the person who (or the entity on behalf of whom you are acting) that is agreeing to these Terms and Conditions.

			4. Intellectual Property Rights and Acceptable Use of the Sites and Services.

			4.1 General Use Rules. The Sites are intended for individuals seeking employment and for employers or recruiters seeking candidates for employment. You may use the Sites only for lawful purposes within the stated context of CareerBuilder's intended and acceptable use of the Sites. CareerBuilder is the sole interpreter of the Sites' intended and acceptable use.

			4.2 CareerBuilder Intellectual Property Rights. The Sites, the CareerBuilder Materials and all right, title and interest in and to the Sites and CareerBuilder Materials are the sole property of CareerBuilder or its licensors, and are protected by United States and foreign copyright, trademark and other laws. Except for the limited licenses expressly granted to you in these Terms and Conditions, CareerBuilder reserves for itself and its licensors all other rights, title and interest. Without limitation on the foregoing, you may not reproduce, modify, display, sell, or distribute the Content or CareerBuilder Materials, or use them in any other way for public or commercial purpose. Notwithstanding anything to the contrary contained herein, this prohibition includes: (a) copying or adapting the HTML code used to generate web pages on the Sites; (b) using or attempting to use engines, manual or automated software, tools, devices, agents, scripts, robots or other means, devices, mechanisms or processes (including, but not limited to, browsers, spiders, robots, avatars or intelligent agents) to navigate, search, access, "scrape," "crawl," or "spider" any web pages or any Services provided on the Sites other than the search engine and search agents available from CareerBuilder on such CareerBuilder Sites and other than generally available third party web browsers (e.g., Internet Explorer, Firefox, Safari); and (c) aggregating, copying or duplicating in any manner any of the Content or information available from any of the CareerBuilder Sites, without the express written consent of CareerBuilder. The use of the Content on any other web site or in a networked computer environment for any purpose is strictly prohibited. The CareerBuilder Materials are not considered to be works for hire and you may duplicate such CareerBuilder Materials only for the purposes outlined in the Service Activation Agreement. "CareerBuilder," "Personified", the CareerBuilder design logo and certain other names or logos are service marks or trademarks of CareerBuilder, and all related product and service names, design marks and slogans are the service marks or trademarks of CareerBuilder. In addition, the "look" and "feel" of the Sites (including color combinations, button shapes, layout, design and all other graphical elements) are also protected by CareerBuilder's trademarks, service marks and copyrights. Any code that CareerBuilder creates to generate or display the Content or the pages making up the Sites is also protected by CareerBuilder's copyright. You must retain all copyright, trademark, service mark and other proprietary notices contained on the Content or CareerBuilder Materials on any authorized copy you make of the Content or CareerBuilder Materials. All other product and service marks contained on the Sites are the trademarks of their respective owners.

			4.3 License to Use by Users who are Job Seekers. CareerBuilder hereby grants you a limited, terminable, non-exclusive right to access and use the Sites only for your personal use seeking employment opportunities for yourself. This authorizes you to view and download a single copy of the material on the Sites solely for your personal, noncommercial use. You agree that you are solely responsible for the content of any Document you post to a Site and any consequences arising from such posting. Your use of the Sites is a privilege. CareerBuilder reserves the right to suspend or terminate that privilege for any reason at any time, in its sole discretion.

			4.4 License to Use by Users who are Employers. CareerBuilder hereby grants you a limited, terminable, non-exclusive right to access and use the Sites only for your internal business use seeking candidates for employment. This authorizes you to view and download a single copy of the material on the Sites solely for your personal use directly related to searching for and recruiting job prospects. CareerBuilder also grants you a limited, terminable, non-exclusive license to use the CareerBuilder Materials and Services for your internal use only. You may not sell, transfer or assign any of the Services or your rights to any of the Services provided by CareerBuilder to any third party without the express written authorization of CareerBuilder. You agree that you are solely responsible for the content of any Document you post to a Site and any consequences arising from such posting. CareerBuilder reserves the right to suspend or terminate your access and use at any time if CareerBuilder determines that you are in breach of these Terms and Conditions.

			4.5 Employer Materials. Employer represents, warrants and covenants that any Employer Materials provided by Employer for use in connection with the Services will not violate any laws or regulations or third-party proprietary rights, including, without limitation, copyright, trademark, obscenity, rights of publicity or privacy, and defamation laws. Employer hereby grants CareerBuilder a non-exclusive, worldwide, royalty-free license to use the Employer Materials and to hyperlink to Employer's website in connection with the Services.

			4.6 Use of Aggregate Data. You understand and agree that CareerBuilder owns and has the right to collect, extract, compile, synthesize, and analyze Aggregate Data. CareerBuilder may use such Aggregate Data for any lawful business purpose without a duty of accounting to you, provided that the data and information is used only in an aggregated and anonymized form so that it cannot be identifiable as relating to you, your Company or to any other Job Seekers. "Aggregate Data" means de-identified aggregated data or information regarding Job Seekers' educational or career history (including, by way of example and not limitation, aggregate data relating to Job Seekers' occupation, location, salary, education and experience).

			4.7 Other Specific Rules Regarding Site Usage. You represent, warrant and agree that you (a) are at least 13 years of age or older, and if under the age of 18 or the age of majority as that is defined in your jurisdiction, you will only use the Sites and Services under the supervision of a parent, legal guardian, or other responsible adult; and (b) will not use (or plan, encourage or help others to use) the Sites for any purpose or in any manner that is prohibited by these Terms and Conditions or by applicable law. It is your responsibility to ensure that your use of the Sites complies with these Terms and Conditions and all applicable laws.

			4.8 User Submissions. CareerBuilder welcomes your comments regarding the Services and the Sites and appreciates hearing from you. Please note, however, that CareerBuilder does not accept or consider creative ideas, suggestions, inventions or materials other than those which it has specifically requested. If you submit feedback on the Services, please be specific in your comments and do not submit creative ideas, inventions, suggestions, or materials. If, despite this notice, you send CareerBuilder creative suggestions, ideas, drawings, concepts, inventions, or other information (a "User Submission"), you understand and agree that the User Submission shall become the property of CareerBuilder. User Submission and any elements contained in User Submissions, shall not be subject to any obligation of confidentiality on CareerBuilder's part, and CareerBuilder will not be liable for any use or disclosure of any User Submission. CareerBuilder shall exclusively own all now known or later discovered rights to the User Submission and shall be entitled to unrestricted use of the User Submission for any purpose whatsoever, commercial or otherwise, without compensation to you or any other person.

			5. Third Party Providers. You acknowledge and agree that CareerBuilder may provide the Services using third party providers, including subcontractors and consultants (the "Third Party Providers"). You agree that, as between CareerBuilder and its Third Party Providers, CareerBuilder will have sole responsibility for handling all billing and contract negotiations.

			6. Disclaimers and Limitations on CareerBuilder's Liability.

			6.1 Allocation of Responsibility CareerBuilder assumes no responsibility for Documents posted by Users and no responsibility for the activities, omissions or other conduct of Users. CareerBuilder acts as a portal for the online distribution and publication of User submitted information and has no obligation to screen communications or information in advance and is not responsible for screening or monitoring Documents posted by Users. If notified by a User of a Document which allegedly does not conform to these Terms and Conditions, CareerBuilder may investigate the allegation and determine in good faith and in its sole discretion whether to remove or request the removal of such Document. CareerBuilder has no liability or responsibility to Users for performance or nonperformance of such activities. CareerBuilder may take any action with respect to User submitted information that it deems necessary or appropriate, in its sole discretion.

			6.2 No endorsements by CareerBuilder. Nothing on the Sites shall be considered an endorsement, representation or warranty with respect to any User or third party, whether in regards to its web site, products, services, hiring, experience, employment or recruiting practices, or otherwise.

			6.3 WARRANTY DISCLAIMERS.

			(a) THE SITES ARE PROVIDED ON AN 'AS IS' BASIS WITHOUT ANY WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. CAREERBUILDER, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIMS ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT OF THIRD PARTIES' RIGHTS, AND FITNESS FOR A PARTICULAR PURPOSE. CAREERBUILDER MAKES NO WARRANTIES ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE SITES.

			(b) WITHOUT LIMITATION ON THE FOREGOING:

			(i) CAREERBUILDER DOES NOT WARRANT THAT THE SITES WILL OPERATE ERROR-FREE OR THAT THE SITES AND THEIR SERVERS ARE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL MECHANISMS. IF YOUR USE OF THE SITES RESULTS DIRECTLY OR INDIRECTLY IN THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA, CAREERBUILDER IS NOT RESPONSIBLE FOR THOSE COSTS.

			(ii) CareerBuilder makes no representations or guarantees regarding the truthfulness, accuracy, LEGALITY, completeness, timeliness or reliability of any Documents posted by Users, or of any other form of communication engaged in by Users. Documents may contain inaccuracies or typographical errors. You agree that any reliance on Documents posted by Users, or on any other form of communication with Users, will be at your own risk.

			(iii) CareerBuilder makes no representations or guarantees regarding the Content of the SiteS, including, but not limited to, broken links, inaccuracies or typographical errors.

			(iv) CAREERBUILDER MAKES NO REPRESENTATIONS OR GUARANTEES REGARDING THE EFFECTIVENESS OF THE SERVICES OR TIMELINESS OF THE SERVICES IN MEETING YOUR EMPLOYMENT OBJECTIVES. CAREERBUILDER DOES NOT GUARANTEE THAT THE SERVICES WILL RESULT IN CANDIDATES BEING HIRED, POSITIONS BEING FILLED OR EMPLOYEES BEING RETAINED, AND IS NOT RESPONSIBLE OR LIABLE FOR ANY BUSINESS, EMPLOYMENT, HIRING AND/OR SALARY DECISIONS, FOR WHATEVER REASON MADE, MADE BY YOU.

			6.4 DAMAGE LIMITATIONS, ALLOCATIONS OF LIABILITY AND EQUITABLE RELIEF.

			(a) YOU ASSUME ALL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SITES, THE INTERNET GENERALLY, AND THE DOCUMENTS OR EMPLOYER MATERIALS THAT YOU POST, PROVIDE OR ACCESS AND FOR YOUR CONDUCT ON AND OFF THE SITES.

			(b) IN NO EVENT SHALL CAREERBUILDER (OR ANY OF ITS OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUBSIDIARIES, AFFILIATES, AGENTS OR ADVERTISERS), BE LIABLE FOR ANY NON-DIRECT DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL AND CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA, LOST EMPLOYMENT OPPORTUNITY, OR BUSINESS INTERRUPTION) RESULTING FROM OR ARISING UNDER OR IN CONNECTION WITH SERVICES OR THE USE OR ACCESS TO, OR THE INABILITY TO USE OR ACCESS, THE SITES AND/OR ANY DOCUMENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT CAREERBUILDER IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

			(c) BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE LIMITATIONS SET FORTH IN THE PRECEDING PARAGRAPH MAY NOT APPLY TO YOU. IF ANY ARE HELD INAPPLICABLE OR UNENFORCEABLE FOR ANY REASON, THEN CAREERBUILDER'S MAXIMUM LIABILITY TO YOU FOR ANY NON-DIRECT TYPE OF DAMAGES SHALL BE LIMITED TO U.S. $200.00 IN THE AGGREGATE.

			(d) IN NO EVENT SHALL CAREERBUILDER (OR ANY OF ITS OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUBSIDIARIES, AFFILIATES, AGENTS OR ADVERTISERS), BE LIABLE FOR ANY DIRECT DAMAGES IN EXCESS IN THE AGGREGATE OF US$200.00 (OR, IF YOU ARE AN EMPLOYER WITH A SERVICES AGREEMENT WITH CAREERBUILDER, THE AMOUNTS ACTUALLY PAID BY YOU TO CAREERBUILDER UNDER THIS AGREEMENT IF GREATER THAN US$200.00).

			(e) Due to the nature of this Agreement, in addition to money damages, you agree that CareerBuilder will be entitled to equitable relief upon a breach of this agreement by you.

			6.5 User Authentication. Because User authentication on the Internet is difficult, CareerBuilder cannot and does not confirm that each User is who they claim to be. Because CareerBuilder does not and cannot be involved in User-to-User dealings or control the behavior of participants on the Sites, in the event that you have a dispute with one or more Users, you release CareerBuilder from claims, demands and damages (actual and consequential and direct and indirect) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes.

			6.6 California Residents. If you are a California resident, you waive California Civil Code Section 1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor."

			7. Data Protection. If you are an Employer, this Section 7 applies

			7.1 To the extent that the provision of the Services under this Agreement involves the processing of Employer Personal Data by CareerBuilder as a processor on behalf of Employer as a data controller under GDPR, CareerBuilder's Data Protection Addendum is incorporated into, and hereby forms a part of, this Agreement.

			7.2 To the extent that the provision of the Services under this Agreement involves personal data subject to GDPR other than Employer Personal Data, such data is provided by CareerBuilder as a data controller to Employer as a data controller for the Intended Purpose and:

			(a) CareerBuilder warrants that it has an adequate legal basis under GDPR for sharing that data with Employer for the uses permitted by Section 4.4; and

			(b) Employer will comply with GDPR and any other applicable data protection laws with respect to such data, including (i) processing such data fairly and lawfully and only for the Intended Purpose; (ii) processing such data only for as long as is necessary for the Intended Purpose and deleting such data once the Intended Purpose has been fulfilled; (iii) having in place appropriate technical and organizational measures to protect such data against accidental or unlawful destruction or accidental loss, alternation, unauthorized disclosure or access, and which provide a level of security appropriate to the risk represented by the processing and the nature of the data; (iv) having in place procedures so that any third party it authorizes to have access to such data, including processors, will respect and maintain the confidentiality and security of the data; (v) not disclosing or transferring such data to a third party located outside of the European Economic Area or Switzerland unless it does so in compliance with all applicable data protection laws; and (vi) complying with data subject requests received by it for access to, or correction, amendment, blocking or deletion of, such data made pursuant to applicable data protection laws.

			7.3 For the purposes of this Section 7, "GDPR" means the Regulation (EU) 2016/679 of the European Parliament and of the Council of the 27 April 2016 on the protection of natural persons with regards to the processing of personal data and on the free movement of such data as applicable as of 25 May 2018 as may be amended from time to time, together with all laws and regulations implementing the same in any European Member State and "Employer Personal Data" means personal data concerning Job Seekers that has been uploaded by Employer or by a Job Seeker directly to the Services operated by CareerBuilder solely on behalf of the Employer and subject to GDPR with respect to the processing of such personal data.

			8. Links to Other Sites. CareerBuilder contains links to third party web sites. These links are provided solely as a convenience to you and not as an endorsement by CareerBuilder of the contents on such third-party web sites. CareerBuilder is not responsible for the content of linked third-party sites and does not make any representations regarding the content or accuracy of materials on such third-party web sites. If you decide to access linked third-party web sites, you do so at your own risk.

			9. Amendments to this Agreement and Changes to Sites. CareerBuilder may revise these Terms and Conditions at any time by updating this page. Changes will be binding on you on the date they are posted on the Sites (or as otherwise stated in the any notice of such changes). Any use of a Site will be considered acceptance by you of the then-current Terms and Conditions (including any exhibits thereto) contained on such Site. If at any time you find the Terms and Conditions unacceptable, you may not use the applicable Site any longer. Any new or different terms supplied by you are specifically rejected by CareerBuilder unless CareerBuilder agrees to them in a signed writing specifically including those new or different terms. CareerBuilder may change the Sites at any time.

			10. Indemnity. You agree to defend, indemnify, and hold harmless CareerBuilder (and its subsidiaries, affiliates, officers, directors, employees and agents) from and against any third party claims, actions or demands (including, without limitation, costs, damages and reasonable legal and accounting fees) alleging or resulting from or in connection with your use of the Sites, any Document posted by you, your use of the Services or your breach of this Agreement. CareerBuilder shall use reasonable efforts to provide you prompt notice of any such claim, suit, or proceeding and may assist you, at your expense, in defending any such claim, suit or proceeding.

			11. User Information and Privacy Policy.

			11.1 When you register on any of the CareerBuilder Sites or in connection with the Services, you will be asked to create an account and provide CareerBuilder with certain information, including but not limited to, a valid email address ("User Information"). You acknowledge and agree that you have no ownership rights in your account.

			11.2 All User Information will be used in accordance with the terms of CareerBuilder's Privacy Policy. Please note, as set forth in the Privacy Policy, that CareerBuilder may collect certain User Information and may contact Users periodically in accordance with the terms of the Privacy Policy. In addition, CareerBuilder reserves the right to comply, in its sole discretion, with legal requirements, requests from law enforcement agencies or requests from government entities, even to the extent that such compliance may require disclosure of certain User Information. In addition, third parties may retain cached copies of User Information.

			12. Questions and Notices. Questions concerning the use of the Sites should be directed to Feedback. Notices to CareerBuilder should be sent to the address listed on the Sites. We will send notice to you at the address submitted by you or to such other address as CareerBuilder reasonably determines is an appropriate address for you.

			13. General. CareerBuilder contact information is listed on the Sites. CareerBuilder makes no claims that the Content is appropriate or may be downloaded outside of the United States. Access to the Content may not be legal by certain persons or in certain countries, and such persons have no right to access or use the Sites. If you access CareerBuilder from outside of the United States, you do so at your own risk and are responsible for compliance with the laws of your jurisdiction. This Agreement and your Service Activation Agreement, if you have one, are governed by the internal substantive laws of the State of Illinois, without respect to its conflict of laws principles. Jurisdiction for any claims arising under this Agreement or your Service Activation Agreement shall lie exclusively with the state or federal courts in the State of Illinois. The sole relationship between you and CareerBuilder is that of independent contractors. If any provision of this Agreement is found to be invalid by any court having competent jurisdiction, the invalidity of all or part of a provision shall not affect the validity of the remaining parts and provisions of this Agreement, which shall remain in full force and effect. All provisions of this Agreement shall survive termination except those granting access or use to the Sites, and you shall cease all your use and access thereof immediately. You may not assign or transfer your obligations under this Agreement. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term. Except as expressly provided by CareerBuilder in a particular "Legal Notice," or material on particular web pages of the Sites, this Agreement and your Service Activation Agreement where applicable, constitute the entire agreement between you and CareerBuilder.

			14. Rules regarding Posting, Conduct and Security.

			The following rules apply to your use of the Sites and/or the Services. The list of rules is for illustration only and is not a complete list of all posting, conduct and security rules.

			14.1 Posting Rules:

			(a) You may not post any Document to a Site that contains: (i) URLs or links to web sites other than to recruitment related pages on your company web site (to advertise your company or web site, see our Advertising Info page.); (ii) copyrighted material (unless you own the copyright or have the owner's permission to post the copyrighted material); (iii) trade secrets (unless you own them or have the owner's permission to post them); (iv) material that infringes on or misappropriates any other intellectual property rights, or violates the privacy or publicity rights of others; (v) irrelevant keywords or white text keywords (including any words embedded in the Document and hidden from the User); (vi) anything that is discriminatory, sexually explicit, obscene, libelous, defamatory, threatening, harassing, abusive, or hateful; or (vii) anything that is embarrassing or offensive to another person or entity.

			(b) You may not use a Document(s) to: (i) impersonate another person, living or dead; (ii) post false, inaccurate or misleading information, opinions or notices (commercial or otherwise) or chain letters; (iii) post advertisements, or solicitations of business (including, but not limited to, email processors, any pyramid scheme or "club membership"); provided, however that CareerBuilder may allow posting of certain training and business opportunities (see 14.1(e) below).

			(c) Your Document(s) must contain sufficient detail to convey clearly to the User the nature and requirements of the job opportunity, or, in the case of Users seeking employment, your qualifications as a candidate for employment. Documents that encourage the User to "email for more details" are not permitted.

			(d) Job postings must describe individual openings for traditional W-2 or 1099 employees. You may not advertise multiple job openings in a single posting.

			(e) In limited circumstances, at CareerBuilder's sole discretion, CareerBuilder allows non-traditional job postings such as education/training, business opportunities, franchise, and multi-level marketing opportunities to be posted on the Sites. These non-traditional job postings may require an investment of time and/or money by the User seeking the position. CareerBuilder reserves the right, in its sole discretion, to move, modify, or remove entirely a non-traditional job posting if CareerBuilder deems such job posting to conflict with the best interests of its Users or detract from the User experience.

			(f) Resume postings must contain the accurate resume of a living individual seeking employment on a full-time, part-time, or contractual basis on his or her own behalf.

			(g) CareerBuilder is under no obligation to monitor the Documents posted on the Sites, but it may monitor Documents at random. Documents found to violate the above Posting Rules may be removed at CareerBuilder's sole discretion.

			14.2 Conduct Rules:

			(a) You may not respond to postings by other Users in any manner or for any purpose other than that which is expected (i.e., to apply for the job or to initiate further discussion with the candidate). Communications soliciting the Employer's business are prohibited.

			(b) You may not send unsolicited commercial email to Users.

			(c) Protect your password. Your CareerBuilder account and any related Services accessed through such account are to be accessed and used solely by you. Upon your successful registration for a CareerBuilder account, you will be provided with a unique password that will permit you to access the account. You may not provide your password or otherwise permit access to your CareerBuilder account to any third party. You are responsible for maintaining the confidentiality of your information and password. You agree to protect and keep your password confidential, to change your password on a regular basis, and to maintain appropriate and regularly updated malware scanning and cleaning tools on your network and individual computer(s).You are responsible for all uses of your account, whether or not authorized by you. If others use your password to post inappropriate material on the Sites, you risk losing your access to the Sites. You agree to notify CareerBuilder immediately of any unauthorized use of your account or password.

			(d) Report inappropriate postings or conduct to Feedback

			(e) You may not delete or revise any material posted by any other person or entity.

			(f) If at any time CareerBuilder comes to the understanding that you: (i) misled CareerBuilder regarding your business practices and/or services, or (ii) purchased services that do not represent your precise business, CareerBuilder reserves the right to terminate your Agreement.

			14.3 Security Rules:

			(a) Users are prohibited from violating or attempting to violate the security of the Sites, including, without limitation: (i) accessing data not intended for such User or logging into a server or account which the User is not authorized to access; (ii) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (iii) attempting to interfere with service to any User, host or network, including, without limitation, via means of submitting a virus to the Sites, overloading, "flooding", "mail bombing" or "crashing"; (iv) sending unsolicited e-mail, including promotions and/or advertising of products or services; (v) forging any TCP/IP packet header or any part of the header information in any e-mail or newsgroup posting.

			(b) Violation of these Security Rules may result in civil or criminal liability. CareerBuilder will investigate occurrences which may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting Users who are involved in such violations.

			15. Copyright Complaints.

			15.1 CareerBuilder respects the intellectual property of others. It is CareerBuilder's policy to respond to claims of copyright and other intellectual property infringement. CareerBuilder will promptly process and investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act ("DMCA") and other applicable intellectual property laws. Upon receipt of notices complying with the DMCA, CareerBuilder may act expeditiously to remove or disable access to any material claimed to be infringing or claimed to be the subject of infringing activity and may act expeditiously to remove or disable access to any reference or link to material or activity that is claimed to be infringing. CareerBuilder will terminate access for Users who are repeat infringers.

			15.2 Notifying CareerBuilder of Copyright Infringement: To provide CareerBuilder notice of an infringement, you must provide a written communication to the attention of "Trust and Site Security" care of TSST@careerbuilder.com that sets forth the information specified by the DMCA (http://www.copyright.gov/title17/92chap5.html#512). Please also note that you may be liable for damages (including costs and attorneys' fees) if you materially misrepresent that an activity is infringing your copyright.

			15.3 Providing CareerBuilder with Counter-Notification: If we remove or disable access to content in response to an infringement notice, we will make reasonable attempts to contact the owner or administrator of the affected site or content. If you feel that your material does not constitute infringement, you may provide CareerBuilder with a counter notification by written communication to the attention of "Trust and Site Security" at TSST@careerbuilder.com that sets forth all of the necessary information required by the DMCA (http://www.copyright.gov/title17/92chap5.html#512). Please note that you may be liable for damages (including costs and attorneys' fees) if you materially misrepresent that an activity is not infringing the copyrights of others. If you are uncertain whether an activity constitutes infringement, we recommended seeking advice of an attorney.

			Please note that Sections 16, 17 and 18 below contain terms and conditions that apply to specific Services (Resume Database, Recruitment Edge and Recruitment Analytics) and they are part of this Agreement if you are purchasing or using any of those specific Services or packages that include such Services (Sections 16 and 17 govern use of Standard Search and sections 16, 17 and 18 govern use of Search Pro).

			16. Additional Terms in Connection with Use of Resume Database. If, in your Service Activation Agreement with CareerBuilder, you are purchasing Resume Database access, the following additional terms apply to you:

			16.1 CareerBuilder grants you a limited, personal, terminable, non-transferable, non-exclusive right to access the CareerBuilder Resume Database via the Sites for the purpose of viewing and/or downloading a single copy of available paper and/or video resumes (collectively "Resumes") solely for your use.

			16.2 The Resume Database is to be accessed and used solely by those Users whom you authorize to access the Resume Database through your account (each an "Authorized RDB User"). Each Authorized RDB User will be issued a unique Resume Database Seat (a "Seat") through which they can perform the actions described in 16.1. Each Seat must be purchased in advance by you and may be accessed by using unique login credentials. You are only permitted to assign one Seat per Authorized RDB User and Authorized RDB Users may not share their login credentials or Seat access amongst themselves, with any other co-workers or with any other third parties.

			16.3 Authorized RDB Users may download, one at a time, up to either 50 Resumes per day (per Seat) or 3000 Resumes per month (per Seat) depending on the Resume Database product purchased by you in accordance with the terms of your Agreement. Please note that the term "download" shall include: (i) viewing or clicking on a Resume page; (ii) saving a Resume to a folder; (iii) printing a Resume; (iv) copying a Resume; (v) emailing or forwarding a Resume; and/or (vi) any other action that results or could result in your use of a Resume or any of the information contained therein.

			16.4 Neither you nor your Authorized RDB Users may use the Resume Database in any way which, in CareerBuilder's sole judgment, adversely affects CareerBuilder's business, business prospects, the performance or function of any Site or the Resume Database, or interferes with the ability of other subscribers to access the Resume Database. Further, use of the Resume Database by you or by your Authorized RDB Users may not interfere with or violate, in any manner, the privacy election of CareerBuilder Job Seekers. You understand and agree that any violation of section 16 will give CareerBuilder the right to immediately terminate any and all access to the RDB and to terminate any corresponding Agreements.

			16.5 You and your Authorized RDB Users may use your subscription to the Resume Database only for seeking candidates for employment and are specifically prohibited from using information contained in the Resume Database to (i) sell or promote any products or services, (ii) send emails that, in CareerBuilder's sole judgment, are excessive in frequency or contain job postings that are irrelevant to the work history of particular classes of Job Seekers or (iii) take any other action that is, in CareerBuilder's sole judgment, inconsistent with these Terms and Conditions, misleading or incomplete, or in violation of any Federal, State, Local law, statute, code, rule, or regulation. Company understands and agrees that if Company uses the Resume Database in violation of the preceding restrictions, then CareerBuilder may, at its sole discretion, either terminate Company's Agreement or transfer Company's Seats from the Resume Database to the Targeted Resume Database (a database that only contains individuals whom CareerBuilder has identified as appropriate candidates for sales positions where the majority of the compensation is to be derived from commissions).

			16.6 CareerBuilder may terminate, suspend, update, alter or supplement, at its sole discretion, all or any part of the Resume Database at any time. By permitting access to the CareerBuilder Resume Database, CareerBuilder does not convey any interest in or to the Resume Database or any other CareerBuilder property or Services. All right, title and interest in and to the Resume Database is and shall remain in CareerBuilder.

			17. Additional Terms in Connection with Use of Recruitment Edge Services. If, in your Service Activation Agreement with CareerBuilder, you are purchasing our Recruitment Edge Services, the following additional terms apply to you:

			17.1 Recruitment Edge aggregates data from the open web by scanning professional networking sites, talent hubs, blogs, publications and journals, and scanning social networks to find talent. Recruitment Edge may solely be used for candidate lead generation purposes and to make initial contact with possible candidates and must not be used to evaluate a job applicant's eligibility for employment or a current employee's eligibility for continued employment, reassignment or promotion. You are prohibited from reviewing profiles of persons who are employed by you or who have already expressed interest in employment with you outside of the Recruitment Edge platform. Any information regarding a potential candidate that is obtained from Recruitment Edge is largely derived from public sources and is not guaranteed or verified to be accurate or up to date. Accordingly, such information should not be maintained in the individual's application file or in any subsequent employee file.

			17.2 CareerBuilder grants Company a limited, personal, terminable, non-transferable, non-exclusive right to access Recruitment Edge via the Sites for the purpose of viewing and/or downloading a single copy of available profiles (collectively, "Profiles") solely for Company's internal use. Recruitment Edge is to be accessed and used solely by Company through its authorized Users. Company may download, one at a time, up to either 150 Profiles per day (per Recruitment Edge user license). Please note that the term "download" shall include: (i) viewing or clicking on a Profile page; (ii) saving a Profile to a folder; (iii) printing a Profile; (iv) copying a Profile; (v) emailing or forwarding a Profile; and/or (vi) any other action that results or could result in Company's use of a Profile or any of the information contained therein. In addition, if a search in Recruitment Edge yields a Profile for a potential candidate who is part of the CareerBuilder Search Database, then the search will count against that Search Database Seat's monthly download limit rather than the Recruitment Edge Seat's daily download limit.

			18. Additional Terms in Connection with Use of Recruitment Analytics Services. If, in your Service Activation Agreement with CareerBuilder, you are purchasing any of our Recruitment Analytics Services, the following additional terms apply to you:

			18.1 Use of Reports. CareerBuilder hereby grants you a limited, non-exclusive, non-assignable (except as otherwise provided in this Agreement), worldwide right and license to: (a) store and use any Recruitment Analytics Services for your internal management, reference or informational purposes, and (b) distribute copies of any reports generated by the Recruitment Analytics Services (each a "Report"), subject to the conditions that (i) such copies may be distributed only in printed or static electronic PDF format, (ii) in providing a copy of any Report to a recipient, you may not charge the recipient any kind of fee or other consideration, and (iii) you shall not remove or modify any branding, marks, copyright or trademark notices, or any other notices or disclaimers set forth in any Report without CareerBuilder's prior written consent, or otherwise modify the Report in any way so as to falsely or otherwise misrepresent its content. Further, you may not issue press releases or make other public statements regarding any Report, or the contents or conclusions in same, without the express written consent of CareerBuilder.

			18.2 Use of Your Data. If you have purchased Recruitment Analytics Services, then you may provide CareerBuilder with the names, addresses, telephone numbers, e-mail addresses, resumes and other personally identifiable information of Job Seekers sourced from your own files ("Job Seeker Data"). You hereby grant CareerBuilder a non-exclusive license to use, copy, modify, store, transmit and display Job Seeker Data solely to the extent reasonably required to provide and maintain the Services for Company's use. Notwithstanding the foregoing, you understand and agree that CareerBuilder may derive Aggregate Data from the Job Seeker Data and may use such Aggregate Data in accordance with section 4.6.
			                
      </div>
   </div>
</section>
<!-- End service Area -->
